image: ubuntu:latest
pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
    - mv .public public
  artifacts:
    paths:
    - public/src/proyecto/html/list.html
  only:
  - master
